security:
    password_hashers:
        App\Entity\Doctor:
            algorithm: bcrypt
        App\Entity\Patient:
            algorithm: bcrypt

    providers:
        app_user_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter: email
                password_parameter: password
                csrf_token_id: auth_token
                csrf_parameter: csrf_token
                success_handler: App\Security\LoginSuccessHandler
            logout:
                path: logout
                target: home

    access_control:
        - { path: ^/login,   roles: PUBLIC_ACCESS }
        - { path: ^/doctor,  roles: ROLE_DOCTOR }
        - { path: ^/patient, roles: ROLE_PATIENT }
